name: On Git Tag
on:
  push:
    tags:
      - '*'

jobs:
  check:
    uses: ./.github/workflows/action-check.yml
    with:
      fail-on-lint-warning: 'false'
  deploy:
    uses: ./.github/workflows/action-deploy.yml
    needs: check