name: On Pull Request
on:
  pull_request:
    types: [ opened, synchronize, ready_for_review ]

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  check:
    uses: ./.github/workflows/action-check.yml
    with:
      fail-on-lint-warning: 'false'